using System;
using System.IO;
using Avalonia.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using GoldenSpinner.Models;

namespace GoldenSpinner.ViewModels
{
    /// <summary>
    /// Observable wrapper around <see cref="WheelSlice"/> that adds runtime state:
    /// a loaded <see cref="Bitmap"/> for rendering the image inside the slice.
    /// </summary>
    public partial class WheelSliceViewModel : ViewModelBase
    {
        // ── Observable properties (source-generated by CommunityToolkit) ──────

        [ObservableProperty] private string _label = "Slice";

        [ObservableProperty] private string _colorHex = "#3498DB";

        [ObservableProperty] private string? _imagePath;

        [ObservableProperty] private string? _soundPath;

        /// <summary>
        /// Bitmap loaded from <see cref="ImagePath"/>; null if no image is assigned
        /// or the file could not be read.  Stored separately so it can be disposed.
        /// </summary>
        [ObservableProperty] private Bitmap? _loadedBitmap;

        /// <summary>Relative weight for weighted spinning.</summary>
        [ObservableProperty] private double _weight = 1.0;

        /// <summary>
        /// Whether this slice participates in the wheel.
        /// Ticked = active (shown). Unticked = inactive (excluded).
        /// Automatically set to false when Weight drops to 0.
        /// </summary>
        [ObservableProperty] private bool _isActive = true;


        // ── Identity ──────────────────────────────────────────────────────────

        public string Id { get; } = Guid.NewGuid().ToString();

        // ── Constructors ──────────────────────────────────────────────────────

        public WheelSliceViewModel() { }

        /// <summary>Constructs a ViewModel from a deserialized model and loads the bitmap.</summary>
        public WheelSliceViewModel(WheelSlice model)
        {
            _label    = model.Label;
            _colorHex = model.ColorHex;
            _soundPath = model.SoundPath;
            _weight   = Math.Max(0.0, model.Weight);
            _isActive = model.IsActive;
            // Use the property setter so the bitmap is loaded immediately.
            ImagePath = model.ImagePath;
        }

        // ── Property-change reactions ─────────────────────────────────────────

        /// <summary>
        /// Called automatically by CommunityToolkit whenever <see cref="ImagePath"/> changes.
        /// Disposes the previous bitmap and loads the new one from disk.
        /// </summary>
        partial void OnImagePathChanged(string? value)
        {
            LoadedBitmap?.Dispose();
            LoadedBitmap = null;

            if (string.IsNullOrWhiteSpace(value) || !File.Exists(value)) return;

            try { LoadedBitmap = new Bitmap(value); }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[WheelSliceViewModel] Cannot load image '{value}': {ex.Message}");
            }
        }

        // ── Conversion ────────────────────────────────────────────────────────

        /// <summary>Creates a serialisable <see cref="WheelSlice"/> from the current state.</summary>
        public WheelSlice ToModel() => new()
        {
            Id        = Id,
            Label     = Label,
            ColorHex  = ColorHex,
            ImagePath = ImagePath,
            SoundPath = SoundPath,
            Weight    = Weight,
            IsActive  = IsActive
        };
    }
}
